import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={inter.className}>
        <div className='w-full min-h-screen bg-tea-green '>
          <div className=' min-w-[300px] max-w-7xl  min-h-screen mx-auto  px-2'>
          <Header/>
            {children}
          </div> 
        </div>
      </body>
    </html>
  )
}
